# Find ASCII Code from value 

In [1]:
import string

alpha_chars = {i:ord(i) for i in string.ascii_uppercase}
search_code = 80

for character, code in alpha_chars.items():
    if code == search_code:
        print(character)


P


In [2]:
import numpy as np

arr_1 = np.array([
    [1.2, -0.3, 1.3],
    [1.2, 2., 0.3]
]).astype(np.float64)

In [25]:
np.dot(np.ones(arr_1.shape[1])[:, np.newaxis], np.mean(arr_1, axis=1)[:, np.newaxis].T)


array([[0.73333333, 1.16666667],
       [0.73333333, 1.16666667],
       [0.73333333, 1.16666667]])

In [26]:
np.std(arr_1, axis=1)


array([0.73181661, 0.69442222])

In [3]:
def standardize_data(arr):
    return (arr - np.mean(arr)) / np.std(arr)

standardize_data(arr_1)

array([[ 0.33532638, -1.67663188,  0.46945693],
       [ 0.33532638,  1.40837078, -0.87184858]])

In [8]:
arr_1 - np.transpose(np.mean(arr_1, axis=1))


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 